### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by dirtydother** [SEPIA-Framework/sepia-wakeword-tools#4]
Hi,

I've set up a raspberry with openhab so my next step will be setting up a second raspberry with Respeaker and Sepia for voice interacting with my smart home. So I set up Sepia and the API to OpenHab with chat commands works fine. I also set up the Respeaker and I'm able recording something (arecord).

So the next step will be that I can talk to my Respeaker and Sepia receives the spoken message.

First, I installed the sepia-client on the same Raspberry on which the sepia-server and respeaker are installed. Fortunately you also have a wakeword-tool but unfortunately the python script doesn't work on my rasp :-(

Here are my commands:

mkdir sepia-wakeword
cd sepia-wakeword
wget https://github.com/SEPIA-Framework/sepia-wakeword-tools/archive/0.8.0.zip
unzip 0.8.0.zip
cd sepia-wakeword-tools-0.8.0/Porcupine
python -m sepia.account --id=uid1007 --host=192.168.0.109:20726/sepia

After typing in the password I receive the following error message:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/sepia-wakeword/sepia-wakeword-tools-0.8.0/Porcupine/sepia/account.py", line 142, in <module>
    account.authenticate(p)
  File "/home/pi/sepia-wakeword/sepia-wakeword-tools-0.8.0/Porcupine/sepia/account.py", line 60, in authenticate
    response = requests.request("POST", url, json=payload, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.0.109', port=20726): Max retries exceeded with url: /sepia/assist/authentication (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7610c610>: Failed to establish a new connection: [Errno 111] Connection refused',))

Do you have any idea, in which previous step I did a mistake or what I should check?

Best regards
Björn

**Comment by fquirin** [comment]
Hi Björn,

the stand-alone wake-word tool is a bit older and I haven't used or tested it for a while because the engine is integrated into the SEPIA client as well. In theory, it should still work but I'd have to confirm this first before trying to debug your error.

You can use the integrated tool by activating it via the `~/clexi/www/sepia/settings.js` like this:
```
...
    "useWakeWord": true,
    "autoloadWakeWord": true,
    "allowWakeWordDuringStream": true,
...

```

There is a bit more info [here](https://github.com/SEPIA-Framework/sepia-html-client-app/blob/master/www/xtensions/picovoice/README.md) and a couple of discussions can be found here in this issues section.

**Comment by dirtydother** [comment]
Hi Florian,

ah, ok, thank you very much! :-)
Seems to be more easy then expected ;-)

Best regards
Björn
